In [1]:
# Import modules.
import pandas as pd
import numpy as np
import requests
import random
import gmaps
import citipy
import json
import time

# Import the API key.
from citipy import citipy
from config import weather_key

In [2]:
# 3.Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)
lat_lngs

In [3]:
# 4. Use citypy to generate nearest cities.
# Create a list for holding the cities.
cities = []

# Identify the nearest city for each latitude and longitude combination.
for lat_lngs in lat_lngs:
    city = citipy.nearest_city(lat_lngs[0], lat_lngs[1]).city_name
    
    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count.
len(cities)

746

In [4]:
# API url
#url = 'https://api.openweathermap.org/data/2.5/weather?lat={lats}&lon={lngs}&appid='
#url = "http://api.openweathermap.org/data/2.5/weather?
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_key

In [9]:
# Create an endpoint URL for a city.
city_data = []

# Make API calls
for city in (cities):
    time.sleep(60)

    city_url = url + "&q=" + city.replace(" ","+")

    try:
        city_weather = requests.get(city_url).json()
        # Parse out the max temp, humidity, and cloudiness
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_weather_description = city_weather["weather"][0]["description"]

    
        city_data.append({"City": city.title(), 
                              "Lat": city_lat, 
                              "Lng": city_lng, 
                              "Max Temp": city_max_temp,
                              "Current Description": city_weather_description,
                              "Humidity": city_humidity,
                              "Cloudiness": city_clouds,
                              "Wind Speed": city_wind,
                              "Country": city_country})
    except:
        print("City not found")
        
print("Finished")
#print(city_url)

City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found
City not found

In [10]:
city_data_df = pd.DataFrame(city_data)
city_data_df.head()

,City,Lat,Lng,Max Temp,Current Description,Humidity,Cloudiness,Wind Speed,Country
0,Mitu,1.1983,-70.1733,71.29,few clouds,96,15,0.16,CO
1,College,64.8569,-147.8028,55.09,heavy intensity rain,87,75,9.22,US
2,Sao Jose Da Coroa Grande,-8.8978,-35.1478,73.51,scattered clouds,88,27,8.88,BR
3,Castro,-24.7911,-50.0119,53.17,overcast clouds,96,100,5.91,BR
4,Port-Gentil,-0.7193,8.7815,73.44,light rain,82,100,12.75,GA

In [11]:
new_column_order = ["City", "Country", "Lat",
                    "Lng", "Max Temp", "Humidity", 
                    "Cloudiness", "Wind Speed", 
                    "Current Description"] 


city_data_df = city_data_df[new_column_order]
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Mitu,CO,1.1983,-70.1733,71.29,96,15,0.16,few clouds
1,College,US,64.8569,-147.8028,55.09,87,75,9.22,heavy intensity rain
2,Sao Jose Da Coroa Grande,BR,-8.8978,-35.1478,73.51,88,27,8.88,scattered clouds
3,Castro,BR,-24.7911,-50.0119,53.17,96,100,5.91,overcast clouds
4,Port-Gentil,GA,-0.7193,8.7815,73.44,82,100,12.75,light rain
5,Albany,US,42.6001,-73.9662,81.25,90,28,4.23,scattered clouds
6,Charters Towers,AU,-20.1000,146.2667,75.87,42,54,12.17,broken clouds
7,Kars,TR,40.6020,43.0950,54.05,82,0,4.61,clear sky
8,Qaanaaq,GL,77.4840,-69.3632,39.11,67,10,2.80,clear sky
9,Hithadhoo,MV,-0.6000,73.0833,82.35,72,100,11.36,overcast clouds

In [12]:
output_data_file = "WeatherPy_Database.csv"

city_data_df.to_csv(output_data_file, index_label="City_ID")